const $ = id => document.getElementById(id);
const state = {files:{tender:null,proposal:null,guarantee:null}, result:null, sourceUrl:null, evidence:{}};
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function sample(path,name){const r=await fetch(path);if(!r.ok)throw Error('Could not load sample PDF');return new File([await r.blob()],name,{type:'application/pdf'});}
function setFile(kind,file){state.files[kind]=file;$(kind+'Name').innerHTML=file?`${esc(file.name)} <b>✓</b>`:'Choose a PDF <b>＋</b>';if(kind==='tender'){if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);state.sourceUrl=file?URL.createObjectURL(file):null;} $('addGuarantee').disabled=!state.files.proposal || !!state.files.guarantee;}
['tender','proposal','guarantee'].forEach(kind=>$(kind).addEventListener('change',e=>setFile(kind,e.target.files[0]||null)));
$('loadDemo').onclick=async()=>{try{$('loadDemo').disabled=true;const [t,p]=await Promise.all([sample('/sample/tender.pdf','CNRE_02_2026_official.pdf'),sample('/sample/proposal.pdf','TechVision_fictional_bid.pdf')]);setFile('tender',t);setFile('proposal',p);setFile('guarantee',null);$('error').hidden=true;await runAnalysis();}catch(e){showError(e.message)}finally{$('loadDemo').disabled=false}};
$('addGuarantee').onclick=async()=>{try{setFile('guarantee',await sample('/sample/guarantee.pdf','DEMO_only_guarantee.pdf'));await runAnalysis();}catch(e){showError(e.message)}};
function showError(message){$('error').textContent=message;$('error').hidden=false;}
async function asBase64(file){const buf=await file.arrayBuffer();let binary='';const bytes=new Uint8Array(buf);for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary);}
async function runAnalysis(){if(!state.files.tender||!state.files.proposal)return showError('Add a tender PDF and bid pack PDF first.');const button=$('analyze');button.disabled=true;button.innerHTML='Reading documents…';$('error').hidden=true;try{const body={tender:await asBase64(state.files.tender),proposal:await asBase64(state.files.proposal),guarantee:state.files.guarantee?await asBase64(state.files.guarantee):null,use_ai:$('useAi').checked};const response=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Analysis failed');state.result=result;render(result);$('review').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){showError(e.message)}finally{button.disabled=false;button.innerHTML='Run preflight <span>→</span>';}}
$('analyze').onclick=runAnalysis;
function evidenceButton(id,page,label='View evidence'){return `<button class="source-button" data-evidence="${esc(id)}" data-page="${page}">${esc(label)} ↗</button>`;}
function render(r){$('review').hidden=false;$('simulator').hidden=!r.known_tender;$('room').hidden=!r.known_tender;$('strategy').hidden=!r.known_tender;$('decision').textContent=r.decision;$('reviewSubtitle').textContent=`${r.tender_name} · ${r.company} · ${r.engine}`;$('blockingCount').textContent=r.summary.blocking;$('reviewCount').textContent=r.summary.review;$('clearCount').textContent=r.summary.clear;$('progressValue').textContent=r.summary.progress_pct+'%';$('progressFill').style.width=r.summary.progress_pct+'%';$('reportLink').href=r.report_url;$('packageLink').href=r.package_url;$('sourceDocument').href=state.sourceUrl||'/sample/tender.pdf';$('aiNotice').textContent=r.ai_warning+' '+r.notice;
 $('checks').innerHTML=r.checks.map(c=>`<article class="check"><div class="check-top"><h4>${esc(c.title)}</h4><span class="pill ${esc(c.status)}">${esc(c.status)}</span></div><p>${esc(c.evidence)}</p>${c.action?`<p class="action">Next: ${esc(c.action)}</p>`:''}<div class="check-actions">${evidenceButton(c.id,c.page,`Source · page ${c.page}`)}<button class="source-button" data-why="${esc(c.id)}">${r.ai_explanations[c.id]?'AI explanation':'Why this matters'} ↗</button></div><div class="why-answer" id="why-${esc(c.id)}" hidden></div></article>`).join('')||'<article class="check">This tender is not yet mapped. Review model findings and create verified rules before using the simulator.</article>';
 $('aiCandidates').hidden=!r.ai_findings.length;$('aiCandidates').innerHTML=r.ai_findings.length?'<h3>Local AI candidates · exact quotes verified</h3>'+r.ai_findings.map(x=>`<article class="check"><h4>${esc(x.requirement)}</h4><p>“${esc(x.source_quote)}”</p><a target="_blank" rel="noopener" href="${esc(state.sourceUrl)}#page=${x.source_page}">Original PDF · p.${x.source_page} ↗</a></article>`).join(''):'';
 $('riskMap').innerHTML=r.risks.map((x,i)=>`<button class="risk-card ${esc(x.level)}" data-evidence="${esc(i<4?x.rule_id:'risk_'+i)}" data-page="${x.page}"><span class="risk-kind">${esc(x.kind.toUpperCase())} · ${esc(x.status.toUpperCase())}</span><span class="risk-title">${esc(x.title)}</span><span class="risk-source">Original PDF · p.${x.page} ↗</span></button>`).join('')||'<div class="check">Risk mapping for this uploaded tender requires a person to confirm the clauses.</div>';
 $('rooms').innerHTML=r.rooms.map((x,i)=>`<article class="room"><div class="room-icon">${['▥','▤','▦','◇'][i]}</div><h3>${esc(x.name)}</h3><div class="room-status ${esc(x.status)}">${esc(x.status.toUpperCase())}</div><ul>${x.items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></article>`).join('');
 $('strategyList').innerHTML=r.strategy.map((x,i)=>`<article class="strategy-card"><span class="step">${String(i+1).padStart(2,'0')} / BID FOCUS</span><h3>${esc(x.title)}</h3><b>${esc(x.weight)}</b><p>${esc(x.insight)}</p>${evidenceButton('strategy_'+i,x.page,`Read rubric · p.${x.page}`)}</article>`).join('');
 $('answer').textContent='Ask about a requirement, score, price, team, guarantee, or submission channel.';
}
async function openEvidence(id,page){const r=state.result;if(!r)return;const hit=state.evidence[id];const item=id.startsWith('strategy_')?r.strategy[Number(id.split('_')[1])]:id.startsWith('risk_')?r.risks[Number(id.split('_')[1])]:r.checks.find(x=>x.id===id);$('evidenceTitle').textContent=(item?.title||'Tender source')+' · page '+page;$('evidenceQuote').textContent=item?.source_quote||item?.quote||'';$('pageImage').src=`/evidence/p${page}.png`;$('pdfLink').href=(state.sourceUrl||'/sample/tender.pdf')+'#page='+page;const hl=$('highlight');if(hit){hl.hidden=false;hl.style.left=(hit.x*100)+'%';hl.style.top=(hit.y*100)+'%';hl.style.width=(Math.max(hit.w,.045)*100)+'%';hl.style.height=(Math.max(hit.h,.016)*100)+'%';}else hl.hidden=true;$('evidenceDialog').showModal();}
document.addEventListener('click',e=>{const evidence=e.target.closest('[data-evidence]');if(evidence)openEvidence(evidence.dataset.evidence,Number(evidence.dataset.page));const why=e.target.closest('[data-why]');if(why)explainCheck(why.dataset.why,why);});$('closeEvidence').onclick=()=>$('evidenceDialog').close();$('evidenceDialog').addEventListener('click',e=>{if(e.target===$('evidenceDialog'))$('evidenceDialog').close()});
async function explainCheck(id,button){const r=state.result;if(!r)return;const box=$('why-'+id);box.hidden=false;box.textContent='Preparing the explanation…';button.disabled=true;try{const response=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis_id:r.analysis_id,check_id:id})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not explain this check');box.innerHTML=`<b>${esc(data.engine)}</b><p>${esc(data.text)}</p><small>Source: original tender PDF, page ${data.source_page}. Review the clause before acting.</small>`;}catch(e){box.textContent=e.message}finally{button.disabled=false}}
function findAnswer(){const r=state.result;if(!r)return $('answer').textContent='Run a review first.';const q=$('question').value.toLowerCase().trim();if(!q)return $('answer').textContent='Enter a question about the tender.';const tokens=q.split(/\W+/).filter(x=>x.length>2);const corpus=[...r.requirements.map(x=>({...x,answer:x.detail,evidence:x.id})),...r.strategy.map((x,i)=>({...x,answer:x.insight,source_quote:x.quote,evidence:'strategy_'+i}))];const ranked=corpus.map(x=>({x,score:tokens.reduce((n,t)=>n+((x.title+' '+x.answer+' '+x.detail+' '+x.source_quote).toLowerCase().includes(t)?1:0),0)})).sort((a,b)=>b.score-a.score);const best=ranked[0];if(!best||!best.score)return $('answer').textContent='No verified mapped answer found. Open the original tender and review it manually.';$('answer').innerHTML=`<strong>${esc(best.x.title)}</strong><br>${esc(best.x.answer)}<br><br><button class="source-button" data-evidence="${esc(best.x.evidence)}" data-page="${best.x.page}">Read source on page ${best.x.page} ↗</button><br><small>Source search over verified rules. This is not a live AI answer.</small>`;}
$('askButton').onclick=findAnswer;$('question').addEventListener('keydown',e=>{if(e.key==='Enter')findAnswer()});
$('runSimulation').onclick=async()=>{const r=state.result;if(!r)return;const changes={};if($('simGuarantee').value!=='current')changes.guarantee_present=$('simGuarantee').value==='present';for(const [id,key] of [['simDays','guarantee_days'],['simAmount','guarantee_amount'],['simTtc','ttc']])if($(id).value!=='')changes[key]=Number($(id).value);if(!Object.keys(changes).length)return $('simOutcome').innerHTML='<span class="small-caps">LIVE SCENARIO</span><h3>Change at least one field.</h3>';try{const response=await fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysis_id:r.analysis_id,changes})});const out=await response.json();if(!response.ok)throw Error(out.error);const delta=out.summary.blocking-r.summary.blocking;$('simOutcome').innerHTML=`<span class="small-caps">SIMULATED RESULT · NOT YOUR UPLOADED BID</span><h3>${esc(out.decision)}</h3><p>${out.summary.blocking} blockers · ${out.summary.review} items still need human review. ${delta<0?'The scenario clears '+Math.abs(delta)+' blocker.':delta>0?'The scenario adds '+delta+' blocker.':'The blocker count is unchanged.'}</p><div class="delta">Checklist progress: ${out.summary.progress_pct}% (scenario only). Your uploaded documents have not changed.</div>`;}catch(e){showError(e.message)}};
$('resetSimulation').onclick=()=>{['simDays','simAmount','simTtc'].forEach(id=>$(id).value='');$('simGuarantee').value='current';$('simOutcome').innerHTML='<span class="small-caps">LIVE SCENARIO</span><h3>Change a field to see the effect.</h3><p>We will compare the proposed values against the mapped tender rules.</p>'};
Promise.all([fetch('/api/health').then(r=>r.json()),fetch('/evidence/map.json').then(r=>r.json())]).then(([health,map])=>{state.evidence=map;const models=health.model.models;$('modelBadge').textContent=models.length?'Local AI installed: '+models.join(', '):'Rules mode · local AI not installed';}).catch(()=>$('modelBadge').textContent='Rules mode');
