const assert = require('node:assert/strict');
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const page = await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8001/',{waitUntil:'networkidle'});
  await page.locator('#useAi').uncheck();
  await page.getByRole('button',{name:/Load sample bid/}).click();
  await page.locator('#decision').waitFor();
  assert.equal(await page.locator('#decision').textContent(),'Blocking issues found');
  assert.equal(await page.locator('#blockingCount').textContent(),'1');
  assert.equal(await page.locator('.risk-card').count(),9);
  assert.equal(await page.locator('#progressValue').textContent(),'67%');
  const reportUrl=await page.locator('#reportLink').getAttribute('href');
  const reportResponse=await page.request.get('http://127.0.0.1:8001'+reportUrl);
  assert.equal(reportResponse.status(),200);
  assert.equal((await reportResponse.body()).subarray(0,5).toString(),'%PDF-');
  const badRequest=await page.request.post('http://127.0.0.1:8001/api/analyze',{data:{tender:'not-base64',proposal:'not-base64'}});
  assert.equal(badRequest.status(),400);
  await page.screenshot({path:'tender_preflight/tests/desktop.png',fullPage:true});
  await page.locator('.risk-card').first().click();
  assert.equal(await page.locator('#evidenceDialog').evaluate(el=>el.open),true);
  assert.match(await page.locator('#evidenceTitle').textContent(),/page 7/);
  assert.equal(await page.locator('#highlight').isVisible(),true);
  await page.locator('#closeEvidence').click();
  await page.locator('#simGuarantee').selectOption('present');
  await page.locator('#simDays').fill('90');
  await page.locator('#simAmount').fill('1000');
  await page.locator('#runSimulation').click();
  await page.locator('#simOutcome').getByText('Blocking issues found').waitFor();
  await page.locator('#simDays').fill('120');
  await page.locator('#runSimulation').click();
  await page.locator('#simOutcome').getByText('Ready for final human review').waitFor();
  await page.locator('#addGuarantee').click();
  await page.locator('#decision').getByText('Ready for final human review').waitFor();
  assert.equal(await page.locator('#blockingCount').textContent(),'0');
  assert.equal(await page.locator('#progressValue').textContent(),'75%');
  const packageUrl=await page.locator('#packageLink').getAttribute('href');
  const packageResponse=await page.request.get('http://127.0.0.1:8001'+packageUrl);
  assert.equal(packageResponse.status(),200);
  assert.equal((await packageResponse.body()).subarray(0,2).toString(),'PK');
  await page.locator('#question').fill('guarantee amount');
  await page.locator('#askButton').click();
  assert.match(await page.locator('#answer').textContent(),/1,000 TND/);
  const mobile = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
  await mobile.goto('http://127.0.0.1:8001/',{waitUntil:'networkidle'});
  await mobile.locator('#useAi').uncheck();
  await mobile.screenshot({path:'tender_preflight/tests/mobile.png',fullPage:true});
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await mobile.getByRole('button',{name:/Load sample bid/}).click();
  await mobile.locator('#decision').waitFor();
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('PASS browser demo, evidence, simulator, real fix, report, review ZIP, bad input, answer, mobile overflow');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
